"""EVDS groups no other adapter reads, one indicator per group, Türkiye only.

The list is generated by `scripts/build_evds_groups.py` (`data/evds_groups.json`): every
downloaded non-archive group that is neither curated nor left out on purpose. Stored the
archive's way — one dimension value per series, unit "source unit" — and parsed by the
same class; see `evds_archive.py` for the checks.
"""

from __future__ import annotations

import json

from ..config import DATA
from .evds_archive import EvdsArchive

GROUPS = json.loads((DATA / "evds_groups.json").read_text(encoding="utf-8"))


class EvdsGroup(EvdsArchive):
    groups = GROUPS


EVDS_GROUP_ADAPTERS = {
    ident: type(
        "Evds" + "".join(p.title() for p in ident.split("_")),
        (EvdsGroup,),
        {"indicator_id": ident},
    )
    for ident in GROUPS
}
